version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: rewear-mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: rewear
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rewear-api
    restart: always
    ports:
      - '5000:5000'
    environment:
      PORT: 5000
      NODE_ENV: production
      MONGODB_URI: mongodb+srv://rakeshkr8685_db_user:FCJdUksOkpeCIyRl@cluster0.abxawlp.mongodb.net/?appName=Cluster0
      JWT_SECRET: supersecret_jwt_key_rewear_enterprise
      JWT_REFRESH_SECRET: supersecret_refresh_jwt_key_rewear
      CLIENT_URL: http://localhost
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rewear-web
    restart: always
    ports:
      - '80:80'
    depends_on:
      - backend

volumes:
  mongo-data:
